### PR TITLE
Organise file into folders

### PR DESCRIPTION
**Pull request by n1ved**
- Structured files into folders 
 - Deleted inputs and outputs of pass1 since they are no longer applicable
 
   
 ### diff : 
```
        renamed:    palindrome.asm -> MM/palindrome.asm
	renamed:    searchCharacter.asm -> MM/searchCharacter.asm
	renamed:    searching.asm -> MM/searching.asm
	renamed:    indexed.c -> OS/file_allocation/indexed.c
	renamed:    linked.c -> OS/file_allocation/linked.c
	renamed:    sequential.c -> OS/file_allocation/sequential.c
	renamed:    single_directory.c -> OS/file_organisation/single_directory.c
	renamed:    two_directory.c -> OS/file_organisation/two_directory.c
	renamed:    basicpg.c -> OS/paging/basicpg.c
	renamed:    demandpg.c -> OS/paging/demandpg.c
	renamed:    segmentpg.c -> OS/paging/segmentpg.c
	deleted:    Pass_1/input.txt
	deleted:    Pass_1/intertab.txt
	deleted:    Pass_1/optab.txt
	deleted:    Pass_1/symtab.txt
	renamed:    absLoader/absolute.c -> SS/loader/absolute/absolute.c
	renamed:    absLoader/input.txt -> SS/loader/absolute/input.txt
	renamed:    Pass_1/pass_1.c -> SS/two_pass_assembler/pass1.c
	renamed:    pass2.c -> SS/two_pass_assembler/pass2.c
```

### CODE REVIEW

**Comment by mathewalex806** [comment]
LGTM

**Review by mathewalex806 — COMMENTED** [review]
why are we removing the input files for pass 1?

**Comment by n1ved** [comment]
Those files used Nikhil's syntax `**` for empty labels and operands this code uses `-` for empty codes 
file names are also different 
I can create new files If we want those

**Comment by mathewalex806** [comment]
No worries then. All good to go.

**Pull request merged**
